apiVersion: v1
kind: Secret
metadata:
  name: phone-book-idp-secret
  namespace: phone-book-security
  labels:
    app.kubernetes.io/name: phone-book-security
type: Opaque
immutable: true
data:
  # In production environments these won't be stored unencrypted like this, but something like
  # https://github.com/bitnami-labs/sealed-secrets would instead be used.
  DATABASE_PASSWORD: 'WDlqJUc/cCM1U0hXNnBjLQ=='