apiVersion: v1
kind: Service
metadata:
  name: phone-book-idp-service
  namespace: phone-book-security
  labels:
    app.kubernetes.io/name: phone-book-security
spec:
  selector:
    app.kubernetes.io/name: phone-book-idp-deployment
  ports:
    - port: 8080