name: phone_book
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0
  flutter: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  injectable: ^2.1.2
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  auto_route: ^7.4.0
  retrofit: ^4.0.1
  json_annotation: ^4.8.1
  another_flushbar: ^1.12.30
  infinite_scroll_pagination: ^3.2.0
  shared_preferences: ^2.1.1
  freezed_annotation: ^2.2.0
  email_validator: ^2.1.17
  file_picker: ^5.3.2
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  injectable_generator: ^2.1.6
  auto_route_generator: ^7.1.1
  retrofit_generator: ^7.0.1
  build_runner: ^2.4.5
  flutter_lints: ^2.0.1
  freezed: ^2.3.5

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/