name: phone_book
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  injectable: ^1.5.3
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  dartz: ^0.10.1
  auto_route: ^3.2.4
  retrofit: ^3.0.1+1
  json_annotation: ^4.4.0
  another_flushbar: ^1.10.28
  infinite_scroll_pagination: ^3.1.0
  shared_preferences: ^2.0.13
  freezed_annotation: ^1.1.0
  email_validator: ^2.0.1
  file_picker: ^4.5.1
  http_parser: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5
  injectable_generator: ^1.5.3
  auto_route_generator: ^3.2.3
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.8
  flutter_lints: ^1.0.4
  freezed: ^1.1.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/