spring:
  # Liquibase configuration properties.
  # By default, the Spring Boot integration of Liquibase expects the db.changelog-master file to be in YAML format.
  # Therefore, you need to specify the path to the file explicitly if you want to use one of the other supported formats
  # (like XML in this case).
  liquibase.change-log: db/changelog/db.changelog-master.xml

  # Spring Boot configuration for JPA.
  jpa:
    # Don't let the HTTP session keep the database session (Open Session in View pattern).
    # This is an anti-pattern. More is explained at https://vladmihalcea.com/the-open-session-in-view-anti-pattern/
    open-in-view: false
    # To use the single 'hibernate_sequence' sequence as with Hibernate < 6.0.
    # See: https://docs.jboss.org/hibernate/orm/6.0/migration-guide/migration-guide.html#id-sequence-table-name
    properties:
      hibernate.id.db_structure_naming_strategy: legacy

  # Pagination configuration for Spring (Boot) Data.
  data.web.pageable:
    # Make the page parameter start from 1 instead of 0.
    one-indexed-parameters: true
    # Limit the size of the single page to 500 items.
    max-page-size: 500

  # Configuration for the Jackson ObjectMapper serializer and deserializer.
  jackson.default-property-inclusion: non_null

  # Configuration for the handling of multipart requests.
  servlet.multipart:
    # Limit the size of the file(s) uploaded in a request to 5MB (the default is 1MB).
    max-file-size: 5MB

# Configuration properties for the application server.
server:
  # Make active requests complete before stopping the server when receiving the shutdown signal.
  shutdown: graceful

  # Configuration properties for the (Tomcat) embedded application server.
  servlet:
    # Disable the support for JSP since we don't need it (it allows a faster startup).
    jsp.registered: false
    # Context path under which the REST resources will be deployed.
    context-path: /phone-book

# Configuration for the actuator endpoints.
management:
  # Show always the components as well as the details for each component.
  endpoint.health:
      show-components: always
      show-details: always
