# Proxy routing configuration
spring.cloud.gateway:
  default-filters:
  # Headers to remove from the request before forwarding it
  - name: RemoveRequestHeader
    args:
    - name: X-Auth-User
  routes:
  # URL to which the request should be forwarded
  - uri: http://localhost:8081
    predicates:
    # Routes to the contacts web service
    - Path=/phone-book/v*/**
    filters:
    # Preserve the original host in the request (so the one of the proxy, i.e. localhost:8080) instead of setting the
    # one of the target service (so, the one of the backend service, i.e. localhost:8081).
    - PreserveHostHeader
    # Extract the username from the incoming Authorization header and propagate it as the header configured in the
    # default-filters[0].args[0].name property (a.k.a. 'X-Auth-User')
    - AuthenticationIdentityPropagator=${spring.cloud.gateway.default-filters[0].args[0].name}
    # Do not propagate further the Authorization header
    - RemoveRequestHeader=Authorization