apiVersion: v1
kind: ConfigMap
metadata:
  name: phone-book-backend-application-yaml
  namespace: phone-book-services
  labels:
    app.kubernetes.io/name: phone-book-services
immutable: true
data:
  application-prod.yaml: |-
    server.port: 8081
    spring.datasource:
      username: phone-book-user
      password: ${DATABASE_PASSWORD}
      url: jdbc:postgresql://phone-book-database-service.phone-book-database:5432/phone-book-db

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: phone-book-auth-proxy-application-yaml
  namespace: phone-book-services
  labels:
    app.kubernetes.io/name: phone-book-services
immutable: true
data:
  application-prod.yaml: |-
    spring.cloud.gateway:
      default-filters:
      - PreserveHostHeader
      - RemoveRequestHeader=Authorization
      - name: RemoveRequestHeader
        args:
        - name: X-Auth-User
      routes:
      # Containers within the same Pod can communicate by using localhost
      - id: backend-core
        uri: http://localhost:8081
        predicates:
        - Path=/phone-book/v*/**
        filters:
        - AuthenticationIdentityPropagator=${spring.cloud.gateway.default-filters[2].args[0].name}
      - id: backend-actuator
        uri: http://localhost:8081
        predicates:
        - Path=/phone-book/actuator/**
        
