apiVersion: v1
kind: Secret
metadata:
  name: phone-book-backend-secret
  namespace: phone-book-services
  labels:
    app.kubernetes.io/name: phone-book-services
type: Opaque
immutable: true
data:
  # In production environments these won't be stored unencrypted like this, but something like
  # https://github.com/bitnami-labs/sealed-secrets would instead be used.
  DATABASE_PASSWORD: 'bko2TiM4aFQyUHgyakQqeQ=='