apiVersion: v1
kind: Service
metadata:
  name: phone-book-database-service
  namespace: phone-book-database
  labels:
    app.kubernetes.io/name: phone-book-database
spec:
  selector:
    app.kubernetes.io/name: phone-book-database-deployment
  ports:
    - port: 5432
