apiVersion: apps/v1
kind: Deployment
metadata:
  name: phone-book-database-deployment
  namespace: phone-book-database
  labels:
    app.kubernetes.io/name: phone-book-database
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: phone-book-database-deployment
  template:
    metadata:
      name: phone-book-database-pod
      namespace: phone-book-database
      labels:
        app.kubernetes.io/name: phone-book-database-deployment
    spec:
      containers:
        - name: postgres
          image: bitnami/postgresql:14
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: phone-book-database-config-map
            - secretRef:
                name: phone-book-database-secret
          volumeMounts:
            - name: postgres-data
              # Use /bitnami instead of /bitnami/postgresql as specified in the docs of the Docker image.
              # See: https://github.com/bitnami/charts/issues/1210#issuecomment-678759936
              mountPath: /bitnami
            - name: idp-db-init
              mountPath: /docker-entrypoint-initdb.d/init-idp-db.sh
              subPath: init-idp-db.sh
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: 5432
          readinessProbe:
            initialDelaySeconds: 15
            tcpSocket:
              port: 5432
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: phone-book-database-persistent-volume-claim
        - name: idp-db-init
          configMap:
            name: phone-book-idp-db-config-map
            defaultMode: 0744
