apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phone-book-database-persistent-volume-claim
  namespace: phone-book-database
  labels:
    app.kubernetes.io/name: phone-book-database
spec:
  storageClassName: local-path
  resources:
    requests:
      storage: 10Mi
    limits:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce