apiVersion: v1
kind: PersistentVolume
metadata:
  name: phone-book-database-persistent-volume
  namespace: phone-book-database
  labels:
    app.kubernetes.io/name: phone-book-database
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  # local-path is a storage class provided by Rancher k3s that mounts the volume as an hostPath, where the path is under
  # the WSL installation of the k3s cluster. This is accessible from the Windows explorer at \\wsl$
  storageClassName: local-path
  hostPath:
    path: /phone-book-db
  claimRef:
    name: phone-book-database-persistent-volume-claim
    namespace: phone-book-database