apiVersion: v1
kind: Secret
metadata:
  name: phone-book-database-secret
  namespace: phone-book-database
  labels:
    app.kubernetes.io/name: phone-book-database
type: Opaque
immutable: true
data:
  # In production environments these won't be stored unencrypted like this, but something like
  # https://github.com/bitnami-labs/sealed-secrets would instead be used.
  POSTGRESQL_PASSWORD: 'bko2TiM4aFQyUHgyakQqeQ=='
  POSTGRESQL_POSTGRES_PASSWORD: 'cG9zdGdyZXM='
  PHONE_BOOK_IDP_PASSWORD: 'WDlqJUc/cCM1U0hXNnBjLQ=='